#define MAXMESSAGECOUNT 16
#define MAXRETRIES 3
#define MESSAGE_HEADER_LENGTH 4

#define MESSAGE_BUFFER_SIZE 27
#define MESSAGE_SIZE MESSAGE_BUFFER_SIZE-MESSAGE_HEADER_LENGTH
#define MESSAGE 0
#define ACKNOWLEDGE 1
#define CONFIRM 2
#define ACKNOWLEDGE_CONFIRM 3